// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
	"flag"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"login/rpc"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
)

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  string loginByPasswd(string username, string passwd, string type,  params)")
	fmt.Fprintln(os.Stderr, "  string loginByToken(string uid, string token, string type,  params)")
	fmt.Fprintln(os.Stderr, "  bool logout(string uid, string token,  params)")
	fmt.Fprintln(os.Stderr, "  bool isOnline(string uid,  params)")
	fmt.Fprintln(os.Stderr, "  bool kickOff(string uid)")
	fmt.Fprintln(os.Stderr, "  string whichNode(string uid)")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	var parsedUrl url.URL
	var trans thrift.TTransport
	_ = strconv.Atoi
	_ = math.Abs
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Parse()

	if len(urlString) > 0 {
		parsedUrl, err := url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}

	cmd := flag.Arg(0)
	var err error
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransport(trans)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactory()
		break
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
		break
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
		break
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	client := rpc.NewLoginServiceClientFactory(trans, protocolFactory)
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}

	switch cmd {
	case "loginByPasswd":
		if flag.NArg()-1 != 4 {
			fmt.Fprintln(os.Stderr, "LoginByPasswd requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		arg25 := flag.Arg(4)
		mbTrans26 := thrift.NewTMemoryBufferLen(len(arg25))
		defer mbTrans26.Close()
		_, err27 := mbTrans26.WriteString(arg25)
		if err27 != nil {
			Usage()
			return
		}
		factory28 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt29 := factory28.GetProtocol(mbTrans26)
		containerStruct3 := rpc.NewLoginServiceLoginByPasswdArgs()
		err30 := containerStruct3.ReadField4(jsProt29)
		if err30 != nil {
			Usage()
			return
		}
		argvalue3 := containerStruct3.Params
		value3 := argvalue3
		fmt.Print(client.LoginByPasswd(value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "loginByToken":
		if flag.NArg()-1 != 4 {
			fmt.Fprintln(os.Stderr, "LoginByToken requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		arg34 := flag.Arg(4)
		mbTrans35 := thrift.NewTMemoryBufferLen(len(arg34))
		defer mbTrans35.Close()
		_, err36 := mbTrans35.WriteString(arg34)
		if err36 != nil {
			Usage()
			return
		}
		factory37 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt38 := factory37.GetProtocol(mbTrans35)
		containerStruct3 := rpc.NewLoginServiceLoginByTokenArgs()
		err39 := containerStruct3.ReadField4(jsProt38)
		if err39 != nil {
			Usage()
			return
		}
		argvalue3 := containerStruct3.Params
		value3 := argvalue3
		fmt.Print(client.LoginByToken(value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "logout":
		if flag.NArg()-1 != 3 {
			fmt.Fprintln(os.Stderr, "Logout requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		arg42 := flag.Arg(3)
		mbTrans43 := thrift.NewTMemoryBufferLen(len(arg42))
		defer mbTrans43.Close()
		_, err44 := mbTrans43.WriteString(arg42)
		if err44 != nil {
			Usage()
			return
		}
		factory45 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt46 := factory45.GetProtocol(mbTrans43)
		containerStruct2 := rpc.NewLoginServiceLogoutArgs()
		err47 := containerStruct2.ReadField3(jsProt46)
		if err47 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.Params
		value2 := argvalue2
		fmt.Print(client.Logout(value0, value1, value2))
		fmt.Print("\n")
		break
	case "isOnline":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "IsOnline requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		arg49 := flag.Arg(2)
		mbTrans50 := thrift.NewTMemoryBufferLen(len(arg49))
		defer mbTrans50.Close()
		_, err51 := mbTrans50.WriteString(arg49)
		if err51 != nil {
			Usage()
			return
		}
		factory52 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt53 := factory52.GetProtocol(mbTrans50)
		containerStruct1 := rpc.NewLoginServiceIsOnlineArgs()
		err54 := containerStruct1.ReadField2(jsProt53)
		if err54 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.Params
		value1 := argvalue1
		fmt.Print(client.IsOnline(value0, value1))
		fmt.Print("\n")
		break
	case "kickOff":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "KickOff requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.KickOff(value0))
		fmt.Print("\n")
		break
	case "whichNode":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "WhichNode requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.WhichNode(value0))
		fmt.Print("\n")
		break
	case "":
		Usage()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
