// Generated by 搬砖工老刘 github.com/liujiahavefun
// DO NOT EDIT!
// Source: session.proto

package session

import (
	"cellnet"
)

func init() {

	// session.proto
	cellnet.RegisterMessageMeta("session.SessionAccepted", (*SessionAccepted)(nil), 2136350511)
	cellnet.RegisterMessageMeta("session.SessionAcceptFailed", (*SessionAcceptFailed)(nil), 1213847952)
	cellnet.RegisterMessageMeta("session.SessionConnected", (*SessionConnected)(nil), 4228538224)
	cellnet.RegisterMessageMeta("session.SessionConnectFailed", (*SessionConnectFailed)(nil), 1278926828)
	cellnet.RegisterMessageMeta("session.SessionClosed", (*SessionClosed)(nil), 2830250790)
	cellnet.RegisterMessageMeta("session.SessionError", (*SessionError)(nil), 3227768243)

}
