// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package rpc

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"smartgo/libs/proto/thrift/gen-go/test2/shared"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = shared.GoUnusedProtection__

const INT32CONSTANT = 9100

var MAPCONSTANT map[string]string

func init() {
	MAPCONSTANT = map[string]string{
		"hello": "world",
		"hi":    "liujia",
	}

}
